version = 0.1
[default.deploy.parameters]
stack_name = "clinnet"
resolve_s3 = true
s3_prefix = "clinnet"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
