version = 0.1
[default.deploy.parameters]
stack_name = "clinnet-emr"
resolve_s3 = true
s3_prefix = "clinnet-emr"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = false
image_repositories = []