Resources:
  AppointmentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub clinnet-appointment-table-${Stage}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: appointmentId
          AttributeType: S
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: appointmentId
          KeyType: RANGE