version = 0.1
[default.deploy.parameters]
stack_name = "sam-clinnet"
resolve_s3 = true
s3_prefix = "sam-clinnet"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=\"dev\""
