AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Clinnet-EMR

  SAM Template for Clinnet-EMR backend services

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - test
      - prod
    Description: Environment name (dev, test, prod)

Globals:
  Function:
    Timeout: 30
    Runtime: python3.12
    MemorySize: 128
    Environment:
      Variables:
        PATIENTS_TABLE: !Ref PatientsTable
        USERS_TABLE: !Ref UsersTable
        SERVICES_TABLE: !Ref ServicesTable
        APPOINTMENTS_TABLE: !Ref AppointmentsTable
        MEDICAL_RECORDS_TABLE: !Ref MedicalRecordsTable
        DOCUMENTS_BUCKET: !Ref DocumentsBucket
        ENVIRONMENT: !Ref Environment
    Architectures:
      - x86_64
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:
  # DynamoDB Tables
  PatientsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub clinnet-patients-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
    # This table stores patient records, with 'id' as the partition key

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub clinnet-users-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  ServicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub clinnet-services-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  AppointmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub clinnet-appointments-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  MedicalRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub clinnet-medical-records-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # S3 Bucket for document storage
  DocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub clinnet-documents-${Environment}-${AWS::AccountId}-${AWS::Region}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: ExpireTemporaryFiles
            Status: Enabled
            ExpirationInDays: 30 # Automatically delete objects after 30 days

  # API Gateway
  ClinicAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment # Use the Environment parameter for stage name
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: false
      GatewayResponses:
        DEFAULT_4XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
        DEFAULT_5XX:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "'*'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization'"
              Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub clinnet-user-pool-${Environment}
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: given_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: family_name
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
        - Name: custom:role # Using custom attribute for role
          AttributeDataType: String
          Mutable: true
          Required: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub clinnet-app-client-${Environment}
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED
      SupportedIdentityProviders:
        - COGNITO

  # Lambda Functions for Services
  GetServicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/services/
      Handler: get_services.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ServicesTable
      Events:
        GetServices:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /services
            Method: get
            Auth:
              Authorizer: NONE # Services endpoint is public

  GetServiceByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/services/
      Handler: get_service_by_id.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ServicesTable
      Events:
        GetServiceById:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /services/{id}
            Method: get
            Auth:
              Authorizer: NONE # Getting a specific service is public

  CreateServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/services/
      Handler: create_service.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ServicesTable
      Events:
        CreateService:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /services
            Method: post
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  UpdateServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/services/
      Handler: update_service.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ServicesTable
      Events:
        UpdateService:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /services/{id}
            Method: put
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  DeleteServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/services/
      Handler: delete_service.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ServicesTable
      Events:
        DeleteService:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /services/{id}
            Method: delete
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  # Lambda Functions for Patients
  GetPatientsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/patients/
      Handler: get_patients.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PatientsTable
      Events:
        GetPatients:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /patients
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer # CHANGED: Protect patient list
    DependsOn: PatientsTable

  GetPatientByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/patients/
      Handler: get_patient_by_id.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref PatientsTable
      Events:
        GetPatientById:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /patients/{id}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer # CHANGED: Protect specific patient

  CreatePatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/patients/
      Handler: create_patient.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
      Events:
        CreatePatient:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /patients
            Method: post
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  UpdatePatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/patients/
      Handler: update_patient.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
      Events:
        UpdatePatient:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /patients/{id}
            Method: put
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  DeletePatientFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/patients/
      Handler: delete_patient.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PatientsTable
      Events:
        DeletePatient:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /patients/{id}
            Method: delete
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  # Lambda Functions for Users (Profiles)
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/users/
      Handler: get_users.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /users
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer # CHANGED: Protect user list

  GetUserByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/users/
      Handler: get_user_by_id.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UsersTable
      Events:
        GetUserById:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /users/{id}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer # CHANGED: Protect specific user

  CreateUserFunction: # Note: This function should likely be removed or repurposed
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/users/
      Handler: create_user.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        # - AmazonCognitoPowerUser # Consider adding Cognito permissions if creating users via SDK
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /users
            Method: post
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  UpdateUserFunction: # Note: This function should likely be removed or repurposed for profile updates only
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/users/
      Handler: update_user.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        # - AmazonCognitoPowerUser # Consider adding Cognito permissions if updating users via SDK
      Events:
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /users/{id}
            Method: put
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  DeleteUserFunction: # Note: This function should likely be removed or trigger Cognito deletion
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/users/
      Handler: delete_user.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable
        # - AmazonCognitoPowerUser # Consider adding Cognito permissions if deleting users via SDK
      Events:
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /users/{id}
            Method: delete
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  # Lambda Functions for Appointments
  GetAppointmentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/appointments/
      Handler: get_appointments.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AppointmentsTable
      Events:
        GetAppointments:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /appointments
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer # CHANGED: Protect appointment list

  GetAppointmentByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/appointments/
      Handler: get_appointment_by_id.lambda_handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AppointmentsTable
      Events:
        GetAppointmentById:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /appointments/{id}
            Method: get
            Auth:
              Authorizer: CognitoAuthorizer # CHANGED: Protect specific appointment

  CreateAppointmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/appointments/
      Handler: create_appointment.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Events:
        CreateAppointment:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /appointments
            Method: post
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  UpdateAppointmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/appointments/
      Handler: update_appointment.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Events:
        UpdateAppointment:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /appointments/{id}
            Method: put
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

  DeleteAppointmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/handlers/appointments/
      Handler: delete_appointment.lambda_handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AppointmentsTable
      Events:
        DeleteAppointment:
          Type: Api
          Properties:
            RestApiId: !Ref ClinicAPI
            Path: /appointments/{id}
            Method: delete
            # Auth uses DefaultAuthorizer (CognitoAuthorizer)

Outputs:
  ClinicAPI:
    Description: "API Gateway endpoint URL for the current environment"
    Value: !Sub "https://${ClinicAPI}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"

  UserPoolId:
    Description: "Cognito User Pool ID"
    Value: !Ref UserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"

  UserPoolClientId:
    Description: "Cognito User Pool Client ID"
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"

  DocumentsBucket:
    Description: "S3 bucket for document storage"
    Value: !Ref DocumentsBucket
    Export:
      Name: !Sub "${AWS::StackName}-DocumentsBucket"

  Region:
    Description: "AWS Region"
    Value: !Ref AWS::Region
    Export:
      Name: !Sub "${AWS::StackName}-Region"