name: Frontend Deployment (deprecated)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Frontend deployment has been consolidated into .github/workflows/cd.yml"
